### ISSUE TITLE
solveEquations is failing with extra symbolic characters

### ISSUE THREAD

**Issue by DominikFle** [together-science/nerdamer-prime#13]
Hello together I found the following bug when working with systems of linear symbolic (symbols to solve for and symbols as constants) equations:
The following snippet should show the problem with "nerdamer": "^1.1.13":

const testEq= ["0=a*c", "0=b"];
const testUnkwowns = ["a", "b"];
constsol = nerdamer.solveEquations(testEq, [...testUnkwowns]);
console.log(sol.toString());
//This outputs:
// a,-c,b,0 
//But expected is:
// a,0,b,0

Interestingly enough the following works:

const testEq= ["0=a/c", "0=b"];
const testUnkwowns = ["a", "b"];
constsol = nerdamer.solveEquations(testEq, [...testUnkwowns]);
console.log(sol.toString());
//This outputs:
// a,0,b,0 
//Expected is:
// a,0,b,0

Also the follwoing works:

const testBalance = ["a*c+d=0", "0=b", "d=0"];
const testUnkwowns = ["a", "b", "d"];
constsol = nerdamer.solveEquations(testEq, [...testUnkwowns]);
console.log(sol.toString());
//This outputs:
// a,0,b,0,d,0
//Expected is:
// a,0,b,0,d,0

**Comment by gunnarmein-ts** [comment]
Thanks for reporting! Will take a look soon.

**Comment by gunnarmein-ts** [comment]
Fixed in 636128f382806eb34b5d03528d32b4b93e6f9535. 

This was an incorrect use of .collectSymbols() which was supposed to gather the linear terms from the equation, but without additional terms or constants it retrieves the individual factors of the single linear term instead. Fixed by providing an alternate .collectSummandTerms() that will not dig into products.

**Comment by DominikFle** [comment]
Thnak you for the quick fix. When using the new version I cant do the import via 
`const nerdamer = require("nerdamer/all.min")`
anymore. Importing the respective modules without the minified version works though

**Comment by gunnarmein-ts** [comment]
Hi Dominik, I will look at this in a few days, please ping me if you haven't heard in a week. We don't use the minified version and I have never looked at how it is built here. Thanks!

**Comment by gunnarmein-ts** [comment]
I pushed an update all.min.js.  In some future, I will replace gulp with esbuild, but for now this is good enough if I remember to run it ;-)

**Comment by DominikFle** [comment]
Thank you again. That was quick again.
