### ISSUE TITLE
[Improvement] Optional Newton-Raphson x0 for systems of equations

### ISSUE THREAD

**Issue by hobeika** [together-science/nerdamer-prime#24]
First, I'd like to thank you for maintaining this awesome project.
I hope this request is at the right place. I'm happy to discuss it elsewhere if need be.
I hope this request is not full of non-sense, do not hesitate to correct me if you see errors or inaccuracies.

I'm using the `solveSystem` function to solve the following system of equations of degree two with 3 unknowns:

```
[
 (176)^2 = (x--54.97)^2 + (y--73.91)^2 + (z--68.78)^2,
 (169)^2 = (x--8.38)^2 + (y-6.19)^2 + (z--70.53)^2,
 (123)^2 = (x-138.84)^2 + (y--21.97)^2 + (z-76.63)^2
]

```
I am doing trilateration in a 3D space. This case has two solutions
(see screen captures).

nerdamer works great and finds one of the two solutions:
[x≈18.5009, y≈-44.5161, z≈88.427](https://nerdamer.com/demo.html?eq=solveEquations%28[%28176%29^2%3D%28x--54.97%29^2%2B%28y--73.91%29^2%2B%28z--68.78%29^2%2C%28169%29^2%3D%28x--8.38%29^2%2B%28y-6.19%29^2%2B%28z--70.53%29^2%2C%28123%29^2%3D%28x-138.84%29^2%2B%28y--21.97%29^2%2B%28z-76.63%29^2]%29)

This case has another solution but nerdamer is not able to find it.
The following python program finds the same result as nerdamer if the initial guess is {0,0,0}.

But, if I change the initial guess to {5000,-5000,-5000} it will find the second solution:
x≈110.21, y≈-100.096, z≈-13.9556

```python
from scipy.optimize import fsolve
# Systems' Coordinates
x1, y1, z1 = ( -54.97, -73.91, -68.78 )
x2, y2, z2 = ( -8.38, 6.19, -70.53 )
x3, y3, z3 = ( 138.84, -21.97, 76.63 )

# Define a function that evaluates the equations
def equations( guess ):
    x, y, z = guess

    return (
        ( x - x1 )**2 + ( y - y1 )**2 + ( z - z1 )**2 - ( 176 )**2,
        ( x - x2 )**2  + ( y - y2 )**2  + ( z - z2 )**2  - ( 169 )**2,
        ( x - x3 )**2 + ( y - y3 )**2 + ( z - z3 )**2 - ( 123 )**2,
    )


# Make SciPy solve the system using an initial guess.
# The initial guess affects which of the "candidates" SciPy finds.
initial_guess = ( 5000, -5000, -5000 )
#initial_guess = ( 0, 0, 0 )

result = fsolve( equations, initial_guess )

# Display the results.
print( "(x, y, z) =", result )
```

WolframAlpha is able to find both solutions:
[{ (176)^2 = (x--54.97)^2 + (y--73.91)^2 + (z--68.78)^2, (169)^2 = (x--8.38)^2 + (y-6.19)^2 + (z--70.53)^2, (123)^2 = (x-138.84)^2 + (y--21.97)^2 + (z-76.63)^2 }](https://www.wolframalpha.com/input?i=%7B+%28176%29%5E2+%3D+%28x--54.97%29%5E2+%2B+%28y--73.91%29%5E2+%2B+%28z--68.78%29%5E2%2C+%28169%29%5E2+%3D+%28x--8.38%29%5E2+%2B+%28y-6.19%29%5E2+%2B+%28z--70.53%29%5E2%2C+%28123%29%5E2+%3D+%28x-138.84%29%5E2+%2B+%28y--21.97%29%5E2+%2B+%28z-76.63%29%5E2+%7D)
Click the _approximate form_ button at the bottom of the page:
x≈18.5009, y≈-44.5161, z≈88.427
x≈110.21, y≈-100.096, z≈-13.9556

Is there currently a way to set up the initial guess for the `solveSystem` function?
I'm not sure but from what I understand of the source code, I believe the start is set to 0:
[Solve.js#L690](https://github.com/together-science/nerdamer-prime/blob/main/Solve.js#L690)
(and maybe [Solve.js#L747 ?](https://github.com/together-science/nerdamer-prime/blob/main/Solve.js#L747))

If we can't do this currently, could you please provide some hints on how to extend this function to be able to provide it?
Do you think it would be difficult to add an `INITIAL_GUESS` setting to the Core so we could find other solutions?

Thanks!

![solution1](https://github.com/together-science/nerdamer-prime/assets/1174140/6ac796f1-c008-477a-9b3e-79c5e4526f87)
![solution2](https://github.com/together-science/nerdamer-prime/assets/1174140/afd92685-091c-4acf-8bf3-10e25202688f)
![solution2b](https://github.com/together-science/nerdamer-prime/assets/1174140/2fb88f11-b793-4105-ad1f-66707d227478)

**Comment by gunnarmein-ts** [comment]
Hi, you are right, and this is the right way to discuss it. The Newton-Raphson solver starts at 0. It wouldn't be too hard to add a parameter or an option, BUT I don't think it would help you. Martin never meant for the solver to give you all solutions to non-linear systems, and the documentation says it stops at the first solution (which is why we never use that functionality in together.math, we built our own solver on top).

I also must admit I don't know how the Newton solver would work in a system rather than just one dimension. I will take a look and get back to you.

**Comment by gunnarmein-ts** [comment]
Ah, there is a multi-d solver at Solve.js 422. And in line 427 there is mention of a option you can set. There is also a link to a   [paper](https://www.lakeheadu.ca/sites/default/files/uploads/77/docs/RemaniFinal.pdf) in line 595.

**Comment by gunnarmein-ts** [comment]
So I guess you could use that settings option to do a grid search. Let me know if that addresses your concern.

**Comment by jiggzson** [comment]
@hobeika, it is possible to set the start position for solving non-linear systems using  the `NON_LINEAR_START` setting. Please see below.

```javascript
nerdamer.set('NON_LINEAR_START', -5000);
let solutions = nerdamer(`solveEquations([
 (176)^2 = (x--54.97)^2 + (y--73.91)^2 + (z--68.78)^2,
 (169)^2 = (x--8.38)^2 + (y-6.19)^2 + (z--70.53)^2,
 (123)^2 = (x-138.84)^2 + (y--21.97)^2 + (z-76.63)^2
])`);
console.log(solutions.toString());
// [x,110.21049215584164,y,-100.09559365749455,z,-13.95555567122898]
```

**Comment by hobeika** [comment]
> So I guess you could use that settings option to do a grid search. Let me know if that addresses your concern.

Thank you for your quick and detailed answer.
I could succesfully test it this morning by setting the NON_LINEAR_START setting to -5000.

Thank you @jiggzson as well for taking the time to test it and share your findings. I didn't find the time to reply earlier and save you the hassle. 

I confirm it works like a charm.

I believe this issue can be closed. 
Thanks again.
