### ISSUE TITLE
Could the code be made to accept the short form latex for fractions such as 1/2 which is \frac12

### ISSUE THREAD

**Issue by rs-mobitech** [together-science/nerdamer-prime#32]
From what I understand, both 

`\frac12`

and 

`\frac{1}{2}`

are valid, but the code here does not accept the short form.

I also note that it's very easy to confuse the Latex parser, are there any plans to look into putting some tests in place, and improving on this section of code? I note that when I look at the code I see this message:

    /**
     * Converts latex to text - Very very very basic at the moment
     * @param {String} e
     * @returns {String}
     */
    libExports.convertFromLaTeX = function (e) {
        var txt = LaTeX.parse(_.tokenize(e));
        return new Expression(_.parse(txt));
    };

**Comment by gunnarmein-ts** [comment]
Hello, and thanks for your issue! I have no current plans to improve that section or create tests for it. In general, even the asciimath main parser has a number of issues, and I am not familiar with the shunting yard algorithm used in Nerdamer. If you plan to contribute some work here, let me know and we can donate a little code from together.math to help with pre-processing and working around issues like this. Also, I am curious to see you mention the mathlive repo here, what is your particular connection? If you are using Mathlive with Nerdamer, you can use it to convert LaTeX to asciimath, and then feed that to Nerdamer. The Mathlive server component can do this outside of a browser.

**Comment by gunnarmein-ts** [comment]
That said, the changes to make it realize things like \frac12 are trivial, so maybe I'll give that a shot

**Comment by gunnarmein-ts** [comment]
In general, I am open to addressing issues likes this if you send me examples that fail.
