### ISSUE TITLE
Wrong result - precision of calculcations

### ISSUE THREAD

**Issue by truebluepl** [together-science/nerdamer-prime#38]
` \left(8+\sqrt{13}\right)\left(8-\sqrt{13}\right)`
should give 51, but gives fraction about 50.(9)

**Comment by gunnarmein-ts** [comment]
Rounding error. .simplify() will not help as simplify doesn't know a whole lot about sqrt, but .expand() will lead it down the right path:
nerdamer("(8+\sqrt(13))(8-\sqrt(13))").expand().text() ==> 51
