### ISSUE TITLE
Power evaluation of positive decimals results to zero

### ISSUE THREAD

**Issue by nexuses-employ** [together-science/nerdamer-prime#39]
I ran into an error where the result of a positive decimal raised to the power of another positive decimal results to zero. I could replicate the same zero result on the Nerdamer's demo page. The results are below. It seems it has to do with the number of decimals used.
4^4 : 256
3.5^3.5 : 80.21178022896629156698
3.53^3.53 : 85.83110624480512341822
3.5354^3.5354 : 86.88597010415324457726
**3.535401^3.535401 : 0**

4^3.535401 : 134.43844961200180151265
4.5^3.535401 : 203.87697182718099495758
4.53^3.535401 : 208.72296693077927731824
4.5354^3.535401 : 209.60393237375664416211
**4.535401^3.535401 : 0**

**Comment by nexuses-employ** [comment]
Can someone assess this? It is a bug, no?

**Comment by gunnarmein-ts** [comment]
Hello, I can reproduce this and it seems like a bug to me. I will add it to the "known flaws" list and do some debugging when I can. There is another bug around here where things inexplicably go to zero, I hope thy are related. 

Thank you for finding this!

**Comment by gunnarmein-ts** [comment]
Slightly simpler repro:

`nerdamer("3.535401^3.5").evaluate().text()`

**Comment by nexuses-employ** [comment]
On NERDAMER demo page https://nerdamer.com/demo.html your example
3.535401^3.5 results to 83.08744063715216923732

**Comment by gunnarmein-ts** [comment]
nerdamer.com runs the original (archived) nerdamer project. It is possible that this bug is a regression. To try this with nerdamer-prime, run test.js here, or if you are so inclined, go to math.together.science, sign in as a guest, create a new document, open the debugger, and enter the repro into the console there.

**Comment by gunnarmein-ts** [comment]
BTW lest you think that I am in charge of nerdamer.com, I am not.

**Comment by nexuses-employ** [comment]
I was indeed thinking you were in charge of nerdamer, but I do not think that anymore :-)
I ran into this error as a user and thought it be wise to report, hence I searched around where to report ...
You could be the right person to bring this to the right forum, no?

**Comment by gunnarmein-ts** [comment]
You did the right thing, absolutely! I don't know when I will get to debug this. If you have any interest in tracing this yourself, go ahead and holler with any questions.

**Comment by nexuses-employ** [comment]
BTW lest you think that I am a developer, I am not. I just created a git acoount to be able to report the issue.

**Comment by gunnarmein-ts** [comment]
It might be that Nerdamer is converting to floating point too soon (this is just one data point):

<img width="418" alt="image" src="https://github.com/together-science/nerdamer-prime/assets/86687645/c622e1cc-5cde-47cd-99e4-3acf01e012b1">

**Comment by nexuses-employ** [comment]
The code above has a negative exponent.
The example I gave to illustrate the faulty zero outcome, has a positive base and a positive exponent. In such a case there is no division that could lead to a zero result.

**Comment by gunnarmein-ts** [comment]
Nerdamer will represent every number as a fraction internally.
`nerdamer("3.1415^3.5")`
becomes
`(31415/10000)^3.5`
becomes
`(31415^3.5)*(10000^-3.5)`
(Nerdamer's "normal form"). And the denominator of that, in your case, evaluates to float 0.

I wasn't trying to argue with you, I am just leaving breadcrumbs here for when I have time to really debug this.

**Comment by nexuses-employ** [comment]
Thanks for explaining, I did not understand where the negative exponent came from.
It seems to me that the issue is a design one then, no?

**Comment by gunnarmein-ts** [comment]
Too early to say. If you want my gut feeling, I'd say this will turn out to be a simple bug.

**Comment by gunnarmein-ts** [comment]
Fixed. Just a couple of places that converted to decimals when they couldn't afford to.

**Comment by nexuses-employ** [comment]
Great, that's good news. Can I test somewhere? On the Nerdamer demo/test page 3.53540109^3.5 still results to zero?

**Comment by gunnarmein-ts** [comment]
I don't own Nerdamer.com and cannot update it. Martin has retired from the project, even if the site is still up. I'll think about where you can test it without writing code and get back to you. What are you using it for?

**Comment by gunnarmein-ts** [comment]
I see. You might want to contact the mathpad guy to consider using nerdamer-prime instead of nerdamer, he would pick up about 50 bug fixes (a couple of bugs are pretty severe). He maintains his own fork with some 5 LaTeX enhancements, and might or might not be amenable. He should feel free to reach out to me at info@together.science if he has questions. Good luck! (I will still find you a way to easily test nerdamer-prime.)

**Comment by gunnarmein-ts** [comment]
It would not be much work to add what he did for the LaTeX to nerdamer-prime here.

**Comment by nexuses-employ** [comment]
Thanks for all the help and suggestions. I have created an issue with https://github.com/Canna71/obsidian-mathpad/issues/22. Hoping for a positive outcome.
