### ISSUE TITLE
Derivative of inverse trig functions ignores coefficient

### ISSUE THREAD

**Issue by ethansocal** [together-science/nerdamer-prime#40]
When evaluating something such as `diff(4acos(x))` or `diff(4*acos(x))`, it only returns the derivative of arccos. However, if it uses product rule, such as `diff(4x * acos(x))`, it works correctly.

**Comment by gunnarmein-ts** [comment]
Thanks for finding this. I will take a look.

**Comment by gunnarmein-ts** [comment]
This is now fixed. Thanks!
