### ISSUE TITLE
I've just pushed a snapshot to NPM

### ISSUE THREAD

**Issue by nickkolok** [together-science/nerdamer-prime#41]
I'm not sure if I've done it correct, but here you are:
[nerdamer-41fb3b2](https://www.npmjs.com/package/nerdamer-41fb3b2)

I have no right to use the name `nerdamer-prime`, so I just pushed a snapshot. This is a temporary solution, but as for me, it looks not worse than using the original archived repo, that is now also a snapshot.

**Comment by gunnarmein-ts** [comment]
Thanks! I will take a look.

**Comment by gunnarmein-ts** [comment]
I approved your PR, sadly now your snapshot is 3 fixes behind ;-) Some time soon, I will add npm publishing back into the process. Thanks!
