### ISSUE TITLE
IDEA - simplify adding function

### ISSUE THREAD

**Issue by MrHIDEn** [together-science/nerdamer-prime#48]
I think I could add support for simplify function adding.
- instead
```javascript
nerdamer.setFunction('f', ['x'], 'x^2 + 2*x + 1');
```
- this
```javascript
nerdamer.setFunction('f(x)=x^2 + 2*x + 1');
```

Of course it will left previous version of setFunction along with new one.

**Comment by gunnarmein-ts** [comment]
done and published ...
