### ISSUE TITLE
solveEquation bug with term like x*(b+1)

### ISSUE THREAD

**Issue by mderumaux** [together-science/nerdamer-prime#52]
I'm using nerdamer-prime-main downloaded yesterday on firefox.

If I try to solve 2 equations system as : 
LE=['x*b+y=1', 'x+y=6']
LV=["x","y"]
S=nerdamer.solveEquations(LE,[...LV])

all is fine and S is : 
[ "x", "(-b^(-1)+1)^(-1)*b^(-2)-6*(-b^(-1)+1)^(-1)*b^(-1)+b^(-1)" ]
[ "y", "-(-b^(-1)+1)^(-1)*b^(-1)+6*(-b^(-1)+1)^(-1)" ]
which I suppose true.

Then if I try to solve : 
LE=['x*(b+1)+y=1', 'x+y=6']
LV=["x","y"]
S=nerdamer.solveEquations(LE,[...LV])

the solution is wrong as x depends of x itself :
[ "x", "(-b^(-1)+1)^(-1)*b^(-2)-(-b^(-1)+1)^(-1)*b^(-2)*x-6*(-b^(-1)+1)^(-1)*b^(-1)-b^(-1)*x+b^(-1)" ]
[ "y", "(-b^(-1)+1)^(-1)*b^(-1)*x-(-b^(-1)+1)^(-1)*b^(-1)+6*(-b^(-1)+1)^(-1)" ]

I could investigate in the Solve.js file and could catch the bug : 
 - At line 609, toLHS() transform 1st equation to "-1+b*x+x+y" : note that there is 2 terms with x now.
 - At line 750, equs is expanded in e array :  4 elements.
 - At lines 752 and 756, double for loop across variable and equations terms to build the m matrix.
 - at line 770, if term contains the actual v variable, it is stored in m and removed from e. For i=0 (x var) and k=1 (second term) : "b*x" is found and get removed, e has 3 elements. But k is still equal to 1.
 - next loop for k=2, this is "y" that is worked on and "x" term has been ignored. Therefore it is not removed from e and ends in second member c... 

I could fix the bug by adding on line 771 : k--
so that after removing an element in e, index is also decreased to avoid to forget a term.
Another way of fixing that bug may be to factorize x variable before looking for x term, so that there is only one x term with (b+1) coefficient.

With my small fix, result seems OK as there is no more x variable in the result :
[ "x", "((-(1+b)^(-1)+1)^(-1)*(1+b)^(-1)+1)*(1+b)^(-1)-6*(-(1+b)^(-1)+1)^(-1)*(1+b)^(-1)" ]
[ "y", "-(-(1+b)^(-1)+1)^(-1)*(1+b)^(-1)+6*(-(1+b)^(-1)+1)^(-1)" ]

Best regards,
Marc

**Comment by gunnarmein-ts** [comment]
I am going with your fix on 771. Obviously the loop has to hit that spot in the array again next loop. Thanks!

**Comment by gunnarmein-ts** [comment]
Fixed in nerdamer-prime@1.1.16. Thanks!

**Comment by gunnarmein-ts** [comment]
Make that 1.1.17
