### ISSUE TITLE
Error processing equation: TypeError: e.updateHash is not a function

### ISSUE THREAD

**Issue by imvahn** [together-science/nerdamer-prime#55]
Hi,
This issue seems to be happening whenever I try to use the nerdamer.diff function. Here is my code:

```
"use client";

import { useEffect } from "react";
const nerdamer = require("nerdamer-prime/all.min");

interface Props {
  equation: string;
}

const ExtremaFinder = ({ equation }: Props) => {
  useEffect(() => {
    if (!equation) {
      // If equation is undefined or empty, do nothing
      return;
    }

    try {
      console.log("Equation:", equation);
      var e = nerdamer.convertFromLaTeX(equation);
      console.log("Equation not latex:", e.toString());
      const d1 = nerdamer.diff(nerdamer(e), "x");
      // const d1 = nerdamer.diff(nerdamer("ln(x)"), "x");
      var d2 = nerdamer.diff(e, "x", 2);
      console.log("Second Derivative:", d2.toString());
      var cp = d1.solveFor("x");
      console.log("Critical Points:", cp.toString());
    } catch (error) {
      console.error("Error processing equation:", error);
    }
  }, [equation]);

  return <div></div>;
};

export default ExtremaFinder;
```

This is the error I get:

> Error processing equation: TypeError: e.updateHash is not a function
    f all.min.js:1
    diff all.min.js:1
    callfunction nerdamer.core.js:6277
    linker nerdamer.core.js:12887
    block nerdamer.core.js:1267
    linker nerdamer.core.js:12886
    ExtremaFinder ExtremaFinder.tsx:21
    commitHookEffectListMount react-dom.development.js:21102

**Comment by gunnarmein-ts** [comment]
I'll take a look! But off the top of my head, why are you differentiating an equation?

**Comment by gunnarmein-ts** [comment]
BTW the natural log in nerdamer is "log()", not "ln()"

**Comment by imvahn** [comment]
I'm trying to do the first and second derivative tests on equations so I can isolate their vertex points. I've got it connected to a desmos API, and I'm graphing the equations on desmos and using nerdamer to interpret the equations at the same time. Thanks for the tip about log! I was actually thinking of log base 2 or base 10, but I also wasn't really playing around with that as much. I haven't been able to make it past x^2.

**Comment by gunnarmein-ts** [comment]
Ok, I added the ability to differentiate equations (will diff both sides) in version 1.2.2
